name: datascience_6
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - plotly
  - scikit-learn
  - dask
  - dask-ml
  - rdkit
  - jupyterlab
  - ipykernel
  - notebook
  - bokeh
  - numba
  - pyarrow
  - pip
  - pip:
      - chemparse
